authorized(RESCUER_ID, PATIENT_ID) :- request(RESCUER_ID, PATIENT_ID), rescuer(RESCUER_ID).
		
response(RESCUER_ID, PATIENT_ID, NAME, SURNAME, BLOOD_GROUP) :- authorized(RESCUER_ID, PATIENT_ID), 
	data(PATIENT_ID, NAME, SURNAME, BLOOD_GROUP).